---
title: "Lab1"
author: "Anastasia Galperina"
date: "2/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
3+3
```

```{r}
3 + 3 / 3
```

```{r}
(3 + 3) / 3
```

```{r}
log (10)
```

```{r}
exp(2)
```

```{r}
3^3 
```

```{r}
 sqrt (9)
```

```{r}
abs (1-7)
```

```{r}
x <- 3
x
```

```{r}
my_genome_size <- 3100000000
my_genome_size
```

```{r}
x <- 3.5
x
```

```{r}
sqrt(x)
```

```{r}
x <- 3.33
y <- as.integer(x)
y
```

```{r}
x <- 1; y <- 2 
z = x > y 
z 
```

```{r}
x <- TRUE; y <- FALSE 
x & y
```

```{r}
x <- TRUE; y <- FALSE 
x & y
x | y 
!x
```

```{r}
DNA <- "ATGAAA"
DNA
```

```{r}
x <- 1 + 2i 
x
```

```{r}
x<- c(1,10,100)    
x
x * 2
sum (x)
```

```{r}
x<- c(1,10,100) 
y<- c(1,2,3) 
x * y
```

```{r}
codons<- c("AUG", "UAU", "UGA") 
codons
```

# Excercises
```{r}
x <- 3
y <- 15
 
x + y
y - x
x - y
x * y
y / x
x / y
```

```{r}
x <- 2
x <- 3

(x^5) > (y^4)
```

```{r}
vector <- c(22, 62, 148, 43, 129)
vector / (sum(vector))
```

```{r}
nuc <- c("A","T","C","G")
sort(nuc)
```

